server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://son.cqu5fhfcagzh.ap-northeast-2.rds.amazonaws.com/db_project_time_control
    username: admin
    password: 1q2w3e4r    
        
mybatis:
  mapper-locations:
    - /mappers/*.xml
   